version: '3.3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - overlay
    tty: true
    volumes:
      - .:/app
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
    networks:
      - overlay
networks:
  overlay: